spring.application.name=cobranca


spring.jpa.hibernate.ddl-auto=validate


spring.datasource.url=jdbc:postgresql://localhost:5432/cobranca
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver